import { parseArgs, requireFlag, optionalFlag, okJson, failJson } from "./lib/cli.mjs";
import { readArtifact } from "./lib/artifacts.mjs";
import { ARTIFACTS } from "./lib/contracts.mjs";

import fs from "node:fs";
import { tripDir } from "./lib/paths.mjs";
import { readJsonFile } from "./lib/json.mjs";

function tripFile(tripId) {
  return `${tripDir(tripId)}/trip.json`;
}

function loadTrip(tripId) {
  const p = tripFile(tripId);
  if (!fs.existsSync(p)) return null;
  return readJsonFile(p);
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const cmd = String(args.cmd || "").trim();
  try {
    if (!cmd || cmd === "help") {
      okJson({ commands: ["pre_trip", "daily"] });
      return;
    }

    const tripId = requireFlag(args, "trip-id");
    const trip = loadTrip(tripId);
    if (!trip) return failJson("trip not found");
    const overview = readArtifact(tripId, ARTIFACTS.PLAN_OVERVIEW);
    const details = readArtifact(tripId, ARTIFACTS.PLAN_DETAILS);
    const validation = readArtifact(tripId, ARTIFACTS.ROUTE_VALIDATION);

    if (cmd === "pre_trip") {
      okJson({
        mode: "pre_trip",
        trip_id: tripId,
        stage: trip.stage,
        summary: {
          verdict: validation?.verdict || "",
          chosen_route_id: trip.chosen_route_id || "",
        },
        note: "briefing content is generated by agent; this command exposes inputs for rendering.",
        inputs: { overview, details },
      });
      return;
    }

    if (cmd === "daily") {
      const day = optionalFlag(args, "day", "");
      okJson({
        mode: "daily",
        trip_id: tripId,
        day,
        stage: trip.stage,
        note: "briefing content is generated by agent; this command exposes inputs for rendering.",
        inputs: { overview, details },
      });
      return;
    }

    failJson(`unknown cmd: ${cmd}`);
  } catch (e) {
    failJson(e instanceof Error ? e.message : String(e));
  }
}

main();

